docs: jsx
pushdev-code/react-tutorial pull request #3
Opened 2021-10-26 00:52 UTC by juancho11gm

This PR contains the `JSX` section of the React tutorial repo.

2021-11-02 16:33 UTC, fabianmarinog requested changes

2021-11-02 16:33 UTC, fabianmarinog commented on 2-using-jsx/index.md
> +JSX allows us to write HTML in React, making it easier to write and add HTML in React. JSX produces React “elements” and we will render them to the DOM.
```suggestion
JSX allows us to write HTML in React, making it easier to understand what's happening with the components, just by looking at the JSX part of the component. JSX produces React “elements” and we will render them to the DOM.
```

2021-11-02 16:33 UTC, fabianmarinog commented on 2-using-jsx/index.md
> +Under the hood it's using `React.createElement()`
```suggestion
Under the hood it is using `React.createElement()`
```

2021-11-02 16:33 UTC, fabianmarinog commented on 2-using-jsx/index.md
> +With JSX you can write expressions using curly braces `{ }`.
```suggestion
With JSX you can write expressions using curly braces `{ }`. Everything contained inside the curly braces will be evaluated as Javascript code.
```

2021-11-02 16:33 UTC, fabianmarinog commented on 2-using-jsx/index.md
> +You must use `className` insted of `class`.
```suggestion
You must use `className` instead of `class`.  These reserved words are mandatory to avoid clashing with the ones used in HTML.
```

2021-11-02 16:33 UTC, fabianmarinog commented on 2-using-jsx/index.md
> +const myelement = <h1>I'm { 20 + 1 } years old</h1>;
```suggestion
const myElement = <h1>I'm { 20 + 1 } years old</h1>;
```

2021-11-02 16:33 UTC, fabianmarinog commented on 2-using-jsx/index.md
> +const myelement = <h1 className='Title'>Hello Push!</h1>;
```suggestion
const myElement = <h1 className='Title'>Hello Push!</h1>;
```

2021-11-02 16:33 UTC, fabianmarinog commented on 2-using-jsx/index.md
> +const myelement = <button onClick={greeting}>Click me!</button>;
```suggestion
const myElement = <button onClick={greeting}>Click me!</button>;
```

2021-11-02 16:33 UTC, fabianmarinog commented on 2-using-jsx/index.md
> +const myelement = (
```suggestion
const myElement = (
```

2021-11-02 16:33 UTC, fabianmarinog commented on 2-using-jsx/index.md
> +The HTML code must be wrapped only in ONE top level element.
Explain that you `<></>`  can be used to wrap the elements.

2021-11-02 16:35 UTC, fabianmarinog requested changes

2021-11-02 16:35 UTC, fabianmarinog commented on 2-using-jsx/index.md
> +The HTML code must be wrapped only in ONE top level element.
```suggestion
The HTML code must be wrapped only in ONE top-level element.
```

2021-11-05 01:58 UTC, juancho11gm commented
@fabianmarinog the comments were solved. thank you

2021-11-05 10:20 UTC, fabianmarinog approved these changes

2021-11-05 22:25 UTC, merged