docs: functional components
pushdev-code/react-tutorial pull request #4
Opened 2021-10-27 01:03 UTC by juancho11gm

This PR contains the `functional components` section of the React tutorial repo.

2021-11-02 16:47 UTC, fabianmarinog requested changes

2021-11-02 16:47 UTC, fabianmarinog commented on 4-functional-components/index.md
> +Components let you split the UI into independent, reusable pieces, and think about each piece in isolation. Think about this example:
```suggestion
Components allow to split the UI into independent, reusable pieces and think about each piece in isolation. Think about this example:
```

2021-11-02 16:47 UTC, fabianmarinog commented on 4-functional-components/index.md
> +Youtube website is using a video component that keep its structure. It only changes its content, and the following elements are reused in each video preview:
```suggestion
Youtube website is using a video component that keeps its structure. It only changes its content, and the following elements are reused in each video preview:
```

2021-11-02 16:47 UTC, fabianmarinog commented on 4-functional-components/index.md
> +React lets us define components as classes or functions. So, basically with Functional Components a function will return a Component. Let's look an example:
```suggestion
React lets us define components as classes or functions. So, basically with Functional Components, a function will return a Component. Let's look at an example:
```

2021-11-02 16:47 UTC, fabianmarinog commented on 4-functional-components/index.md
> +`Greeting` is a Functional Component. It's using JSX to render the 'div' element.
```suggestion
`Greeting` is a Functional Component. It uses JSX to render the 'div' element.
```

2021-11-02 16:47 UTC, fabianmarinog commented on 4-functional-components/index.md
> +We can also create Components with arrow functions:
```suggestion
We can also create Components using [arrow functions|https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions]:
```

2021-11-02 16:47 UTC, fabianmarinog commented on 4-functional-components/index.md
> +Now that you now how to create Components, you can use them like this:
```suggestion
Now that you know how to create Components, you can use them like this:
```

2021-11-02 16:47 UTC, fabianmarinog commented on 4-functional-components/index.md
> +- Let's take a look to the [different validators](https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes) provided by PropTypes.
```suggestion
- If you provide a different type it will throw an error.
- Let's take a look at the [different validators](https://reactjs.org/docs/typechecking-with-proptypes.html#proptypes) provided by PropTypes.
```

2021-11-02 16:47 UTC, fabianmarinog commented on 4-functional-components/index.md
> +    function Footer({ description, year }){
```suggestion
    function Footer({ description }){
```

2021-11-02 16:47 UTC, fabianmarinog commented on 4-functional-components/index.md
> +          <Footer description='Made with Love 💙' year={2021}/>
```suggestion
          <Footer description='Made with Love 💙' />
```

2021-11-02 16:47 UTC, fabianmarinog commented on 4-functional-components/index.md
> +7. Push your changes and create the Pull request.
```suggestion
1. In your forked `react-tutorial` repo, create a new branch named `feature/4-functional-components`.
2. Create an `index.html` file within the `4-functional-components` folder.
3. Create a Video Functional Component, that must have the Youtube video properties described in the first section [What is a Component?](#what-is-a-component).
4. You can split the Video component into different components.
5. You should use PropTypes.
6. Create various elements using the Video Component, sending the data through the props.
7. Push your changes and create the Pull Request.
```

2021-11-02 16:50 UTC, fabianmarinog requested changes
one more comment

2021-11-05 02:07 UTC, juancho11gm commented
The comments were addressed. Thank you :) @fabianmarinog

2021-11-05 10:21 UTC, fabianmarinog approved these changes

2021-11-05 22:25 UTC, merged