Docs/class components
pushdev-code/react-tutorial pull request #5
Opened 2021-10-29 20:31 UTC by juancho11gm

This PR contains the Class Components section of the React tutorial repo.

2021-11-02 17:41 UTC, fabianmarinog requested changes

2021-11-02 17:41 UTC, fabianmarinog commented on 5-class-components/index.md
> +- Functional Componets are just a plain JavaScript function that returns JSX.
```suggestion
- Functional Components are a JavaScript function that returns JSX.
```

2021-11-02 17:41 UTC, fabianmarinog commented on 5-class-components/index.md
> +- Class Components: We will need to use the this keyword since we are working with classes.
```suggestion
- Class Components: We will need to use the **this** keyword since we are working with classes.
```

2021-11-02 17:41 UTC, fabianmarinog commented on 5-class-components/index.md
> +- Accessing `props` is different, you need to use **this** keyword to refer them. In Functional Components we were receiving them as parameters.
```suggestion
- Accessing `props` is different, you need to use **this** keyword to refer them. In Functional Components, we were receiving them as parameters.
```

2021-11-02 17:41 UTC, fabianmarinog commented on 5-class-components/index.md
> +- Classes Components: You will need to use ES6 `classes`, `render`/`this` keyword and some other stuff described in the next chapters.
```suggestion
- Classes Components: You will need to use ES6 `classes`, `render`/`this` keyword, and some other stuff described in the next chapters.
```

2021-11-02 17:41 UTC, fabianmarinog commented on 5-class-components/index.md
> +The **state** is a plain JavaScript object where you store proerty values that belongs to each component. You can perform side-effects tasks when the state object changes.
```suggestion
The **state** is a plain JavaScript object where you store property values that belongs to each component. You can perform side-effects tasks when the state object changes.
```

2021-11-02 17:41 UTC, fabianmarinog commented on 5-class-components/index.md
> +It will be discussed depeer in the next section.
```suggestion
It will be discussed deeper in the next section.
```

2021-11-02 17:41 UTC, fabianmarinog commented on 5-class-components/index.md
> +It will be described later in the next chapters. Basically each component will have three main phases in its lifecycle.
```suggestion
It will be described later in the next chapters. Basically, each component will have three main phases in its lifecycle.
```

2021-11-02 17:41 UTC, fabianmarinog commented on 5-class-components/index.md
> +- Mounting, Updating and Unmounting: `useEffect`
```suggestion
- Mounting, Updating, and Unmounting: `useEffect`
```

2021-11-02 17:41 UTC, fabianmarinog commented on 5-class-components/index.md
> +2. Create a `index.html` file within the `5-class-components` folder.
```suggestion
2. Create an `index.html` file within the `5-class-components` folder.
```

2021-11-02 17:41 UTC, fabianmarinog commented on 5-class-components/index.md
> +8. Push your changes and create the Pull request.
```suggestion
8. Push your changes and create the Pull Request.
```

2021-11-02 17:52 UTC, fabianmarinog requested changes

2021-11-02 17:52 UTC, fabianmarinog commented on 5-class-components/index.md
> +   };
you can also mention a good practice that is using destructuring to get the props and to avoid dot accessing across the whole render method, i.e.

const { title } = this.props;
....
<h1>🎵 {title} 🎵</h1>

2021-11-02 17:52 UTC, fabianmarinog commented on 5-class-components/index.md
> +  const cardsComponents = cards.map(card => <Card key={card.id} title={card.title} src={card.src}/>);
Don't forget to mention the importance of using ids as the key property in list elements: https://reactjs.org/docs/lists-and-keys.html

2021-11-05 02:16 UTC, juancho11gm commented on 5-class-components/index.md
> +   };
you're right, I'll do it

2021-11-05 02:26 UTC, juancho11gm commented
The comments were addressed 👍

2021-11-05 10:22 UTC, fabianmarinog approved these changes

2021-11-05 22:25 UTC, merged