docs: basic hooks
pushdev-code/react-tutorial pull request #8
Opened 2021-11-12 00:00 UTC by juancho11gm

This PR contains the Basic Hooks section of the React tutorial repo.

2021-11-12 09:11 UTC, fabianmarinog requested changes

2021-11-12 09:11 UTC, fabianmarinog commented on 9-basic-hooks/index.md
> +- You have to remember to bind the event handlers.
```suggestion

Hooks are a new addition to React 16.8. Hooks are a new API that allows us to have state, and other React features, in `Functional Components`.

- You can still use classes, but hooks are recommended.
- Complex components become hard to understand with Classes.
- Hooks let you split one component into smaller functions based on what pieces are related.
- You have to understand how this works in JavaScript.
- You have to remember to bind the event handlers.
```

2021-11-12 09:11 UTC, fabianmarinog commented on 9-basic-hooks/index.md
> +The React `useState` Hook allows to track state in a function component. `State` generally refers to data or properites that need to be tracking through the application.
```suggestion
The React `useState` Hook allows to track state in a function component. `State` generally refers to data or properties that need to be tracked through the application.
```

2021-11-12 09:11 UTC, fabianmarinog commented on 9-basic-hooks/index.md
> +- Timers.
```suggestion
- We highly recommend visiting the[ Frequently asked questions](https://reactjs.org/docs/hooks-state.html)

## Effect Hook

The `useEffect` Hook allows performing side effects in your components.

Common use cases:
- Fetch data.
- Directly update the DOM.
- Timers.
```

2021-11-12 09:11 UTC, fabianmarinog commented on 9-basic-hooks/index.md
> +The `useRef` hook allows to create a reference to the DOM element. It can be used to access a DOM element directly.
```suggestion
The `useRef` hook allows creating a reference to the DOM element. It can be used to access a DOM element directly.
```

2021-11-12 20:52 UTC, juancho11gm commented
The comments were addressed

2021-11-16 13:20 UTC, fabianmarinog approved these changes

2021-11-22 17:14 UTC, merged